add ActiveModel::Datastore.save_all feature
Agrimatics/activemodel-datastore pull request #27
Opened 2018-04-18 09:50 UTC by shao1555

# Motivation

I want to use bulk insert feature to improve performance.

# Resolution

implement `ActiveModel::Datastore.save_all(entries)`
in case of 500 records insertion, 200x faster than before.

# Remark

I'm not good for English. please feel free to update comment and document :)

2018-04-18 10:14 UTC, shao1555 commented
oh.. I'll fix code style reported by RuboCop.

2018-04-18 12:04 UTC, shao1555 commented
@bmclean please review it.

2018-04-20 02:26 UTC, bmclean commented
Hi @shao1555. I like the concept. Hopefully I will have time to review it in more detail tomorrow.

2018-04-20 19:19 UTC, bmclean commented on README.md
> +To improve performance, you can save many entities at once. (Batch operation)
At this position in the README we have not yet mentioned the concept of parent/ancestor. Let's move this new section down and after Datastore Consistency.

2018-04-21 03:41 UTC, bmclean requested changes
This is some really nice work @shao1555!

2018-04-21 04:32 UTC, bmclean commented on lib/active_model/datastore/batch_operation.rb
> +end
What would we expect this method to return? It is currently returning an array of model objects. Should it return an array of Google::Cloud::Datastore::Entity instead?

Also, is the `results.present?` line needed?

2018-04-27 03:37 UTC, bmclean commented
@shao1555 This is ready for your feedback.

2018-06-20 02:53 UTC, bmclean approved these changes

2021-03-05 08:55 UTC, NielsKSchjoedt commented
Why was this not merged yet?

2021-03-05 14:11 UTC, bmclean commented
Hi @NielsKSchjoedt. This was a proof of concept that was never completed. We left it here in case somebody wanted to pick it up again.

2021-03-05 14:20 UTC, bmclean commented
Also, one thing we have learned since this feature was started is that a batch size of 500 won't always work.

See `entries.each_slice(500).map`

While 500 is the max number of entities that can be passed to Datastore sometimes we hit the size limit first. We should set the default to 250 and allow a batch size to be passed in (up to 500).

2021-03-05 14:33 UTC, NielsKSchjoedt commented
@bmclean great. If I am to finish it I will add both a `save_all` and a `save_all!` method. Where the latter will throw an exception if any objects are invalid. Agree? As for the return value of the methods I can think of several idea. From top of my head I am wondering if something like: `{User#1 => true, User#2 => false}` - a hash where the keys are the ActiveModel records with a value of true or false depending on whether they were successfully persisted or not. What's your thoughts?

2021-03-05 18:08 UTC, bmclean commented
@NielsKSchjoedt Sure, `save_all` and a `save_all!` methods would be ok. Yes, perhaps the return values should be ActiveModel. That way validation errors can be extracted if needed. I like your hash idea with the booleans, that would work. For users that wanted a successful count returned they can run something like `.select { |k, v| v == true }.size` on the result.

2026-02-26 23:35 UTC, closed without merging